import "./globals.css" // Importa o CSS corrigido

export const metadata = {
  title: "Dashboard.js",
  description: "Generated by Next.js",
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>{children}</body>
    </html>
  )
}
